### ISSUE TITLE
f-droid repo does not work

### ISSUE THREAD

**Issue by strk** [LubuWest/Friendiqa#3]
F-droid gives error: no index found

**Comment by susobaco** [comment]
Confirmed, I have the same problem.

**Comment by LubuWest** [comment]
I pushed the new version to fdroid binary repo. Could you test if it works now?

**Comment by strk** [comment]
It's not a problem with a package, but with the repository itself.
When adding "www.ma-nic.de/fdroid/repo" as a repository,
in F-Droid 1.0.2, you get:

    "Error getting index file"

**Comment by LubuWest** [comment]
I cannot reproduce this on F-Droid 1.0.3 on Android 5.1. I deleted and added the repo several times.

**Comment by strk** [comment]
Updating to 1.0.3 did not fix the issue for me. I am on Android 4.4.2

**Comment by strk** [comment]
Upstream ticket exists: https://gitlab.com/fdroid/fdroidclient/issues/845

**Comment by LubuWest** [comment]
What time did you try to download? In apache log I have an ssl handshake error for ssl3 at 13.39 CET. I think that cipher is not valid in my certificate.

**Comment by strk** [comment]
It was about that time, and upstream ticket seems to suggest the same (SSL issue).
But I tried HTTP and also didn't work (although it did not print an error, just did not show any package).

**Comment by LubuWest** [comment]
Http should now work. I put a link to the unencrypted repository in the README.

**Comment by strk** [comment]
Bingo, I can finally install Friendiqa, thanks !
Maybe you need to upgrade your operating system to fix the SSL
issues ? (we had this problem on an old server)

**Comment by LubuWest** [comment]
I think the client tried an ssl3 handshake which I specifically excluded in my certificate due to security reasons. Perhaps old Android versions don't have better cipher suites.

**Comment by strk** [comment]
Perhaps, but as long as you document the issue and keep the non-ssl
protocol available everyone should be happy.
